# Generated by Django 5.1.4 on 2025-01-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dummies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('store_display', 'store_display'), ('fashion', 'fashion'), ('customizable', 'customizable'), ('men', 'men'), ('women', 'women'), ('kids', 'kids'), ('full', 'full'), ('half', 'half')], max_length=40)),
                ('status', models.CharField(choices=[('available', 'available'), ('out', 'out')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('image', models.FileField(blank=True, upload_to='content/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(max_length=10000)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
