# Generated by Django 5.1.4 on 2025-01-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummies',
            name='image_2',
            field=models.FileField(blank=True, upload_to='content/'),
        ),
    ]
