# Generated by Django 5.1.4 on 2025-01-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0002_dummies_image_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummies',
            name='video_1',
            field=models.FileField(blank=True, upload_to='content/'),
        ),
        migrations.AddField(
            model_name='dummies',
            name='video_2',
            field=models.FileField(blank=True, upload_to='content/'),
        ),
        migrations.AlterField(
            model_name='dummies',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
