# Generated by Django 5.1.4 on 2025-01-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0004_vidoes_remove_dummies_video_1_remove_dummies_video_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='vidoes',
            name='title',
            field=models.CharField(default='ag', max_length=200),
            preserve_default=False,
        ),
    ]
